import { Metadata } from "next";

export const metadata: Metadata = {
    title: "About MetaData",
    description: "Generated by create next app",
  };

export default function AboutPAge(){
    return(
        <h2>
            Pagina About
        </h2>
    )
}